# Generated by Django 3.2.19 on 2023-05-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evenment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='evenment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='evenment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evenment',
            name='lieu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evenment',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organiseur',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organiseur',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organiseur',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organiseur',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resevation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resevation',
            name='evenment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservation_app.evenment'),
        ),
        migrations.AddField(
            model_name='resevation',
            name='statut',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resevation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservation_app.client'),
        ),
    ]
