# Generated by Django 3.2.19 on 2023-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0002_auto_20230514_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='evenment',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='organiseur',
            old_name='nom',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
