# Generated by Django 3.2.19 on 2023-05-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0005_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='organiseur',
            name='phone',
        ),
    ]
