# Generated by Django 3.2.19 on 2023-05-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0006_auto_20230518_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organiseur',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
