# Generated by Django 3.2.19 on 2023-05-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0008_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organiseur',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
