# Generated by Django 3.2.19 on 2023-05-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0010_alter_organiseur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenment',
            name='is_Vaide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resevation',
            name='nbr_ticket',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Reservation_app.resevation')),
            ],
        ),
    ]
