# Generated by Django 3.2.19 on 2023-05-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0011_auto_20230519_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resevation',
            new_name='Reservation',
        ),
    ]
