# Generated by Django 3.2.19 on 2023-05-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0012_rename_resevation_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='statut',
        ),
    ]
