# Generated by Django 3.2.19 on 2023-05-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0015_evenment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_valable',
            field=models.BooleanField(default=False),
        ),
    ]
