# Generated by Django 3.2.19 on 2023-06-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0016_reservation_is_valable'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenment',
            name='nbr_ticket_max',
            field=models.IntegerField(null=True),
        ),
    ]
