# Generated by Django 3.2.19 on 2023-06-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0019_auto_20230612_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='montant',
            field=models.FloatField(null=True),
        ),
    ]
