# Generated by Django 3.2.19 on 2023-06-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0020_reservation_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nbr_ticket',
            field=models.IntegerField(null=True),
        ),
    ]
