# Generated by Django 3.2.19 on 2023-06-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0021_reservation_nbr_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
