# Generated by Django 3.2.19 on 2023-06-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0023_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenment',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
