# Generated by Django 3.2.19 on 2023-06-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0024_evenment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type_event',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
