# Generated by Django 3.2.19 on 2023-06-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0025_reservation_type_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenment',
            name='id_organ',
            field=models.IntegerField(null=True),
        ),
    ]
