# Generated by Django 3.2.19 on 2023-06-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0026_evenment_id_organ'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
