# Generated by Django 3.2.19 on 2023-06-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0028_alter_evenment_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenment',
            name='picture',
            field=models.ImageField(blank=True, default='images/m.jpg', null=True, upload_to='images/'),
        ),
    ]
