# Generated by Django 3.2.19 on 2023-06-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0030_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenment',
            name='picture',
            field=models.ImageField(blank=True, default='m.jpg', null=True, upload_to=''),
        ),
    ]
