# Generated by Django 3.2.19 on 2023-06-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0031_alter_evenment_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='id_client',
            field=models.IntegerField(null=True),
        ),
    ]
