# Generated by Django 3.2.19 on 2023-06-25 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0032_notification_id_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='id_client',
        ),
        migrations.AddField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reservation_app.client'),
        ),
    ]
