# Generated by Django 3.2.19 on 2023-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0033_auto_20230625_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiseur',
            name='picture',
            field=models.ImageField(blank=True, default='test.jpeg', null=True, upload_to=''),
        ),
    ]
